BEGIN TRANSACTION;

CREATE DATABASE IF NOT EXISTS xAcademy;
USE xAcademy;

CREATE TABLE User (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL
);

CREATE TABLE Library (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  telefono VARCHAR(255) NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL
);

CREATE TABLE Book (
  id INT PRIMARY KEY AUTO_INCREMENT,
  isbn INT NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  autor VARCHAR(255) NOT NULL,
  year VARCHAR(255) NOT NULL,
  library INT NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  deletelogical BOOLEAN DEFAULT false,
  FOREIGN KEY (library) REFERENCES Library(id)
);

COMMIT;